---

- name: Install common packages
  yum:
    name: ['nano', 'unzip', 'net-tools', 'bind-utils', 'curl', 'telnet']
    state: latest
  with_items:
    - nano
    - unzip
    - net-tools
    - bind-utils
    - curl
    - telnet